In [ ]:
import pandas as pd

In [1]:
df = pd.read_csv('dataset_Facebook.csv',delimiter=';')

NameError: name 'pd' is not defined

In [2]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [5]:
!pip install pandas


Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import pandas as pd


In [7]:
df = pd.read_csv('dataset_Facebook.csv',delimiter=';')

In [8]:
df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136


In [9]:
df.describe()

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,500.000000,500.000000,500.000000,500.000000,500.000000,499.000000,500.00000,5.000000e+02,500.000000,500.000000,500.000000,5.000000e+02,500.000000,500.000000,500.00000,499.000000,496.000000,500.000000
mean,123194.176000,1.880000,7.038000,4.150000,7.840000,0.278557,13903.36000,2.958595e+04,920.344000,798.772000,1415.130000,1.676638e+04,6585.488000,609.986000,7.48200,177.945892,27.266129,212.120000
std,16272.813214,0.852675,3.307936,2.030701,4.368589,0.448739,22740.78789,7.680325e+04,985.016636,882.505013,2000.594118,5.979102e+04,7682.009405,612.725618,21.18091,323.398742,42.613292,380.233118
min,81370.000000,1.000000,1.000000,1.000000,1.000000,0.000000,238.00000,5.700000e+02,9.000000,9.000000,9.000000,5.670000e+02,236.000000,9.000000,0.00000,0.000000,0.000000,0.000000
25%,112676.000000,1.000000,4.000000,2.000000,3.000000,0.000000,3315.00000,5.694750e+03,393.750000,332.500000,509.250000,3.969750e+03,2181.500000,291.000000,1.00000,56.500000,10.000000,71.000000
50%,129600.000000,2.000000,7.000000,4.000000,9.000000,0.000000,5281.00000,9.051000e+03,625.500000,551.500000,851.000000,6.255500e+03,3417.000000,412.000000,3.00000,101.000000,19.000000,123.500000
75%,136393.000000,3.000000,10.000000,6.000000,11.000000,1.000000,13168.00000,2.208550e+04,1062.000000,955.500000,1463.000000,1.486050e+04,7989.000000,656.250000,7.00000,187.500000,32.250000,228.500000
max,139441.000000,3.000000,12.000000,7.000000,23.000000,1.000000,180480.00000,1.110282e+06,11452.000000,11328.000000,19779.000000,1.107833e+06,51456.000000,4376.000000,372.00000,5172.000000,790.000000,6334.000000


In [10]:
subset1= df[['like','share','Category']]
subset1

,like,share,Category
0,79.0,17.0,2
1,130.0,29.0,2
2,66.0,14.0,3
3,1572.0,147.0,2
4,325.0,49.0,2
...,...,...,...
495,53.0,26.0,3
496,53.0,22.0,2
497,93.0,18.0,1
498,91.0,38.0,3


In [11]:
subset2=df[['comment','Total Interactions','Paid','like']]
subset2


,comment,Total Interactions,Paid,like
0,4,100,0.0,79.0
1,5,164,0.0,130.0
2,0,80,0.0,66.0
3,58,1777,1.0,1572.0
4,19,393,0.0,325.0
...,...,...,...,...
495,5,84,0.0,53.0
496,0,75,0.0,53.0
497,4,115,0.0,93.0
498,7,136,0.0,91.0


In [16]:
concat=pd.concat([subset1,subset2])
concat

,like,share,Category,comment,Total Interactions,Paid
0,79.0,17.0,2.0,NaN,NaN,NaN
1,130.0,29.0,2.0,NaN,NaN,NaN
2,66.0,14.0,3.0,NaN,NaN,NaN
3,1572.0,147.0,2.0,NaN,NaN,NaN
4,325.0,49.0,2.0,NaN,NaN,NaN
...,...,...,...,...,...,...
495,53.0,NaN,NaN,5.0,84.0,0.0
496,53.0,NaN,NaN,0.0,75.0,0.0
497,93.0,NaN,NaN,4.0,115.0,0.0
498,91.0,NaN,NaN,7.0,136.0,0.0


In [17]:
concat.sort_values(by=['comment'],ascending=False)

,like,share,Category,comment,Total Interactions,Paid
244,5172.0,NaN,NaN,372.0,6334.0,1.0
460,1546.0,NaN,NaN,146.0,1873.0,0.0
168,1622.0,NaN,NaN,144.0,1974.0,0.0
288,469.0,NaN,NaN,103.0,605.0,0.0
228,367.0,NaN,NaN,64.0,456.0,0.0
...,...,...,...,...,...,...
495,53.0,26.0,3.0,NaN,NaN,NaN
496,53.0,22.0,2.0,NaN,NaN,NaN
497,93.0,18.0,1.0,NaN,NaN,NaN
498,91.0,38.0,3.0,NaN,NaN,NaN


In [18]:
concat.T

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
like,79.0,130.0,66.0,1572.0,325.0,152.0,249.0,325.0,161.0,113.0,...,79.0,105.0,128.0,185.0,125.0,53.0,53.0,93.0,91.0,91.0
share,17.0,29.0,14.0,147.0,49.0,33.0,27.0,14.0,31.0,26.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,2.0,2.0,3.0,2.0,2.0,2.0,3.0,3.0,2.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
comment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,0.0,17.0,10.0,5.0,0.0,4.0,7.0,0.0
Total Interactions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,110.0,152.0,137.0,257.0,176.0,84.0,75.0,115.0,136.0,119.0
Paid,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN


In [19]:
concat.transpose()

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
like,79.0,130.0,66.0,1572.0,325.0,152.0,249.0,325.0,161.0,113.0,...,79.0,105.0,128.0,185.0,125.0,53.0,53.0,93.0,91.0,91.0
share,17.0,29.0,14.0,147.0,49.0,33.0,27.0,14.0,31.0,26.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,2.0,2.0,3.0,2.0,2.0,2.0,3.0,3.0,2.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
comment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,0.0,17.0,10.0,5.0,0.0,4.0,7.0,0.0
Total Interactions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,110.0,152.0,137.0,257.0,176.0,84.0,75.0,115.0,136.0,119.0
Paid,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN


In [15]:
df.shape

(500, 19)

In [20]:
concat.shape

(1000, 6)

In [17]:
import numpy as np

In [18]:
arr = np.array(df[['Post Month','Post Weekday']].head(6))
reshaped = arr.reshape(3,4)
print(reshaped)

[[12  4 12  3]
 [12  3 12  2]
 [12  2 12  1]]


In [13]:
merged = pd.merge(subset1, subset2, on='like')

In [14]:
merged

,like,share,Category,comment,Total Interactions,Paid
0,79.0,17.0,2,4,100,0.0
1,79.0,17.0,2,2,97,1.0
2,79.0,17.0,2,1,97,0.0
3,79.0,17.0,2,4,99,0.0
4,79.0,17.0,2,5,95,0.0
...,...,...,...,...,...,...
1405,91.0,38.0,3,7,136,0.0
1406,91.0,38.0,3,0,119,NaN
1407,91.0,28.0,2,5,122,1.0
1408,91.0,28.0,2,7,136,0.0
